
// File generated by Wsutil Compiler version 1.0098 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _GetNamesOfMethods;
//     struct _GetNamesOfMethodsResponse;
//     struct _GetNamesOfMethodsOfAssayType;
//     struct _GetNamesOfMethodsOfAssayTypeResponse;
//     struct _GetAssayTypesOfAllMethods;
//     struct _GetAssayTypesOfAllMethodsResponse;
//     struct _GetNameOfCurrentMethod;
//     struct _GetNameOfCurrentMethodResponse;
//     struct _GetAssayTypeOfCurrentMethod;
//     struct _GetAssayTypeOfCurrentMethodResponse;
//     struct _GetAssayTypeOfMethod;
//     struct _GetAssayTypeOfMethodResponse;
//     struct _GetNamesOfRunsets;
//     struct _GetNamesOfRunsetsResponse;
//     struct _GetNamesOfRunsetsOfAssayType;
//     struct _GetNamesOfRunsetsOfAssayTypeResponse;
//     struct _GetAssayTypesOfAllRunsets;
//     struct _GetAssayTypesOfAllRunsetsResponse;
//     struct _GetNameOfCurrentRunset;
//     struct _GetNameOfCurrentRunsetResponse;
//     struct _GetAssayTypeOfCurrentRunset;
//     struct _GetAssayTypeOfCurrentRunsetResponse;
//     struct _GetAssayTypeOfRunset;
//     struct _GetAssayTypeOfRunsetResponse;
//     struct _GetMethodNamesOfRunset;
//     struct _GetMethodNamesOfRunsetResponse;
//     struct _SelectMethod;
//     struct _SelectMethodResponse;
//     struct _SelectRunset;
//     struct _SelectRunsetResponse;
//     struct _CreateRunset;
//     struct _CreateRunsetResponse;
//     struct _SetSamplePlateId;
//     struct _SetSamplePlateIdResponse;
//     struct _GetSamplePlateId;
//     struct _GetSamplePlateIdResponse;
//     struct _GetCurrentSamplePlateId;
//     struct _GetCurrentSamplePlateIdResponse;
//     struct _MoveSamplePlateTrayOut;
//     struct _MoveSamplePlateTrayOutResponse;
//     struct _MoveSamplePlateTrayIn;
//     struct _MoveSamplePlateTrayInResponse;
//     struct _StartSelectedRunset;
//     struct _StartSelectedRunsetResponse;
//     struct _StartSelectedRunsetFrom;
//     struct _StartSelectedRunsetFromResponse;
//     struct _PauseRunsetAfter;
//     struct _PauseRunsetAfterResponse;
//     struct _ResumeRunset;
//     struct _ResumeRunsetResponse;
//     struct _ResetRunset;
//     struct _ResetRunsetResponse;
//     struct _AbortScript;
//     struct _AbortScriptResponse;
//     struct _LeaveStandby;
//     struct _LeaveStandbyResponse;
//     struct _SetStandbyAfterFinish;
//     struct _SetStandbyAfterFinishResponse;
//     struct _GetStandbyAfterFinish;
//     struct _GetStandbyAfterFinishResponse;
//     struct _GetNamesOfMaintenanceProcedures;
//     struct _GetNamesOfMaintenanceProceduresResponse;
//     struct _RunMaintenanceProcedure;
//     struct _RunMaintenanceProcedureResponse;
//     struct _GetOperationMode;
//     struct _GetOperationModeResponse;
//     struct _IsChipDocked;
//     struct _IsChipDockedResponse;
//     struct _IsSamplePlateTrayIn;
//     struct _IsSamplePlateTrayInResponse;
//     struct _HasMessage;
//     struct _HasMessageResponse;
//     struct _GetMessage;
//     struct _GetMessageResponse;
//     struct _HasErrors;
//     struct _HasErrorsResponse;
//     struct _GetErrors;
//     struct _GetErrorsResponse;
//     struct _HasWarnings;
//     struct _HasWarningsResponse;
//     struct _GetWarnings;
//     struct _GetWarningsResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

typedef struct _GetNamesOfMethods _GetNamesOfMethods;

// typeDescription: n/a
typedef struct _GetNamesOfMethodsResponse 
{
    unsigned int GetNamesOfMethodsResultCount;
    _Field_size_opt_(GetNamesOfMethodsResultCount)WCHAR** GetNamesOfMethodsResult; // optional
} _GetNamesOfMethodsResponse;

// typeDescription: n/a
typedef struct _GetNamesOfMethodsOfAssayType 
{
    WCHAR* assayType; // optional
} _GetNamesOfMethodsOfAssayType;

// typeDescription: n/a
typedef struct _GetNamesOfMethodsOfAssayTypeResponse 
{
    unsigned int GetNamesOfMethodsOfAssayTypeResultCount;
    _Field_size_opt_(GetNamesOfMethodsOfAssayTypeResultCount)WCHAR** GetNamesOfMethodsOfAssayTypeResult; // optional
} _GetNamesOfMethodsOfAssayTypeResponse;

typedef struct _GetAssayTypesOfAllMethods _GetAssayTypesOfAllMethods;

// typeDescription: n/a
typedef struct _GetAssayTypesOfAllMethodsResponse 
{
    unsigned int GetAssayTypesOfAllMethodsResultCount;
    _Field_size_opt_(GetAssayTypesOfAllMethodsResultCount)WCHAR** GetAssayTypesOfAllMethodsResult; // optional
} _GetAssayTypesOfAllMethodsResponse;

typedef struct _GetNameOfCurrentMethod _GetNameOfCurrentMethod;

// typeDescription: n/a
typedef struct _GetNameOfCurrentMethodResponse 
{
    WCHAR* GetNameOfCurrentMethodResult; // optional
} _GetNameOfCurrentMethodResponse;

typedef struct _GetAssayTypeOfCurrentMethod _GetAssayTypeOfCurrentMethod;

// typeDescription: n/a
typedef struct _GetAssayTypeOfCurrentMethodResponse 
{
    WCHAR* GetAssayTypeOfCurrentMethodResult; // optional
} _GetAssayTypeOfCurrentMethodResponse;

// typeDescription: n/a
typedef struct _GetAssayTypeOfMethod 
{
    WCHAR* methodName; // optional
} _GetAssayTypeOfMethod;

// typeDescription: n/a
typedef struct _GetAssayTypeOfMethodResponse 
{
    WCHAR* GetAssayTypeOfMethodResult; // optional
} _GetAssayTypeOfMethodResponse;

typedef struct _GetNamesOfRunsets _GetNamesOfRunsets;

// typeDescription: n/a
typedef struct _GetNamesOfRunsetsResponse 
{
    unsigned int GetNamesOfRunsetsResultCount;
    _Field_size_opt_(GetNamesOfRunsetsResultCount)WCHAR** GetNamesOfRunsetsResult; // optional
} _GetNamesOfRunsetsResponse;

// typeDescription: n/a
typedef struct _GetNamesOfRunsetsOfAssayType 
{
    WCHAR* assayType; // optional
} _GetNamesOfRunsetsOfAssayType;

// typeDescription: n/a
typedef struct _GetNamesOfRunsetsOfAssayTypeResponse 
{
    unsigned int GetNamesOfRunsetsOfAssayTypeResultCount;
    _Field_size_opt_(GetNamesOfRunsetsOfAssayTypeResultCount)WCHAR** GetNamesOfRunsetsOfAssayTypeResult; // optional
} _GetNamesOfRunsetsOfAssayTypeResponse;

typedef struct _GetAssayTypesOfAllRunsets _GetAssayTypesOfAllRunsets;

// typeDescription: n/a
typedef struct _GetAssayTypesOfAllRunsetsResponse 
{
    unsigned int GetAssayTypesOfAllRunsetsResultCount;
    _Field_size_opt_(GetAssayTypesOfAllRunsetsResultCount)WCHAR** GetAssayTypesOfAllRunsetsResult; // optional
} _GetAssayTypesOfAllRunsetsResponse;

typedef struct _GetNameOfCurrentRunset _GetNameOfCurrentRunset;

// typeDescription: n/a
typedef struct _GetNameOfCurrentRunsetResponse 
{
    WCHAR* GetNameOfCurrentRunsetResult; // optional
} _GetNameOfCurrentRunsetResponse;

typedef struct _GetAssayTypeOfCurrentRunset _GetAssayTypeOfCurrentRunset;

// typeDescription: n/a
typedef struct _GetAssayTypeOfCurrentRunsetResponse 
{
    WCHAR* GetAssayTypeOfCurrentRunsetResult; // optional
} _GetAssayTypeOfCurrentRunsetResponse;

// typeDescription: n/a
typedef struct _GetAssayTypeOfRunset 
{
    WCHAR* runsetName; // optional
} _GetAssayTypeOfRunset;

// typeDescription: n/a
typedef struct _GetAssayTypeOfRunsetResponse 
{
    WCHAR* GetAssayTypeOfRunsetResult; // optional
} _GetAssayTypeOfRunsetResponse;

// typeDescription: n/a
typedef struct _GetMethodNamesOfRunset 
{
    WCHAR* runsetName; // optional
} _GetMethodNamesOfRunset;

// typeDescription: n/a
typedef struct _GetMethodNamesOfRunsetResponse 
{
    unsigned int GetMethodNamesOfRunsetResultCount;
    _Field_size_opt_(GetMethodNamesOfRunsetResultCount)WCHAR** GetMethodNamesOfRunsetResult; // optional
} _GetMethodNamesOfRunsetResponse;

// typeDescription: n/a
typedef struct _SelectMethod 
{
    WCHAR* methodName; // optional
} _SelectMethod;

// typeDescription: n/a
typedef struct _SelectMethodResponse 
{
    BOOL SelectMethodResult;
} _SelectMethodResponse;

// typeDescription: n/a
typedef struct _SelectRunset 
{
    WCHAR* runsetName; // optional
} _SelectRunset;

// typeDescription: n/a
typedef struct _SelectRunsetResponse 
{
    BOOL SelectRunsetResult;
} _SelectRunsetResponse;

// typeDescription: n/a
typedef struct _CreateRunset 
{
    unsigned int methodNamesCount;
    _Field_size_opt_(methodNamesCount)WCHAR** methodNames; // optional
} _CreateRunset;

// typeDescription: n/a
typedef struct _CreateRunsetResponse 
{
    BOOL CreateRunsetResult;
} _CreateRunsetResponse;

// typeDescription: n/a
typedef struct _SetSamplePlateId 
{
    int methodIndex;
    WCHAR* plateId; // optional
} _SetSamplePlateId;

// typeDescription: n/a
typedef struct _SetSamplePlateIdResponse 
{
    BOOL SetSamplePlateIdResult;
} _SetSamplePlateIdResponse;

// typeDescription: n/a
typedef struct _GetSamplePlateId 
{
    int methodIndex;
} _GetSamplePlateId;

// typeDescription: n/a
typedef struct _GetSamplePlateIdResponse 
{
    WCHAR* GetSamplePlateIdResult; // optional
} _GetSamplePlateIdResponse;

typedef struct _GetCurrentSamplePlateId _GetCurrentSamplePlateId;

// typeDescription: n/a
typedef struct _GetCurrentSamplePlateIdResponse 
{
    WCHAR* GetCurrentSamplePlateIdResult; // optional
} _GetCurrentSamplePlateIdResponse;

typedef struct _MoveSamplePlateTrayOut _MoveSamplePlateTrayOut;

// typeDescription: n/a
typedef struct _MoveSamplePlateTrayOutResponse 
{
    BOOL MoveSamplePlateTrayOutResult;
} _MoveSamplePlateTrayOutResponse;

typedef struct _MoveSamplePlateTrayIn _MoveSamplePlateTrayIn;

// typeDescription: n/a
typedef struct _MoveSamplePlateTrayInResponse 
{
    BOOL MoveSamplePlateTrayInResult;
} _MoveSamplePlateTrayInResponse;

typedef struct _StartSelectedRunset _StartSelectedRunset;

// typeDescription: n/a
typedef struct _StartSelectedRunsetResponse 
{
    BOOL StartSelectedRunsetResult;
} _StartSelectedRunsetResponse;

// typeDescription: n/a
typedef struct _StartSelectedRunsetFrom 
{
    int methodIndex;
} _StartSelectedRunsetFrom;

// typeDescription: n/a
typedef struct _StartSelectedRunsetFromResponse 
{
    BOOL StartSelectedRunsetFromResult;
} _StartSelectedRunsetFromResponse;

// typeDescription: n/a
typedef struct _PauseRunsetAfter 
{
    int pauseMode;
} _PauseRunsetAfter;

// typeDescription: n/a
typedef struct _PauseRunsetAfterResponse 
{
    BOOL PauseRunsetAfterResult;
} _PauseRunsetAfterResponse;

typedef struct _ResumeRunset _ResumeRunset;

// typeDescription: n/a
typedef struct _ResumeRunsetResponse 
{
    BOOL ResumeRunsetResult;
} _ResumeRunsetResponse;

typedef struct _ResetRunset _ResetRunset;

// typeDescription: n/a
typedef struct _ResetRunsetResponse 
{
    BOOL ResetRunsetResult;
} _ResetRunsetResponse;

typedef struct _AbortScript _AbortScript;

// typeDescription: n/a
typedef struct _AbortScriptResponse 
{
    BOOL AbortScriptResult;
} _AbortScriptResponse;

typedef struct _LeaveStandby _LeaveStandby;

// typeDescription: n/a
typedef struct _LeaveStandbyResponse 
{
    BOOL LeaveStandbyResult;
} _LeaveStandbyResponse;

// typeDescription: n/a
typedef struct _SetStandbyAfterFinish 
{
    BOOL goToStandby;
} _SetStandbyAfterFinish;

// typeDescription: n/a
typedef struct _SetStandbyAfterFinishResponse 
{
    BOOL SetStandbyAfterFinishResult;
} _SetStandbyAfterFinishResponse;

typedef struct _GetStandbyAfterFinish _GetStandbyAfterFinish;

// typeDescription: n/a
typedef struct _GetStandbyAfterFinishResponse 
{
    BOOL GetStandbyAfterFinishResult;
} _GetStandbyAfterFinishResponse;

typedef struct _GetNamesOfMaintenanceProcedures _GetNamesOfMaintenanceProcedures;

// typeDescription: n/a
typedef struct _GetNamesOfMaintenanceProceduresResponse 
{
    unsigned int GetNamesOfMaintenanceProceduresResultCount;
    _Field_size_opt_(GetNamesOfMaintenanceProceduresResultCount)WCHAR** GetNamesOfMaintenanceProceduresResult; // optional
} _GetNamesOfMaintenanceProceduresResponse;

// typeDescription: n/a
typedef struct _RunMaintenanceProcedure 
{
    WCHAR* procedureName; // optional
} _RunMaintenanceProcedure;

// typeDescription: n/a
typedef struct _RunMaintenanceProcedureResponse 
{
    BOOL RunMaintenanceProcedureResult;
} _RunMaintenanceProcedureResponse;

typedef struct _GetOperationMode _GetOperationMode;

// typeDescription: n/a
typedef struct _GetOperationModeResponse 
{
    int GetOperationModeResult;
} _GetOperationModeResponse;

typedef struct _IsChipDocked _IsChipDocked;

// typeDescription: n/a
typedef struct _IsChipDockedResponse 
{
    int IsChipDockedResult;
} _IsChipDockedResponse;

typedef struct _IsSamplePlateTrayIn _IsSamplePlateTrayIn;

// typeDescription: n/a
typedef struct _IsSamplePlateTrayInResponse 
{
    int IsSamplePlateTrayInResult;
} _IsSamplePlateTrayInResponse;

typedef struct _HasMessage _HasMessage;

// typeDescription: n/a
typedef struct _HasMessageResponse 
{
    BOOL HasMessageResult;
} _HasMessageResponse;

typedef struct _GetMessage _GetMessage;

// typeDescription: n/a
typedef struct _GetMessageResponse 
{
    unsigned int GetMessageResultCount;
    _Field_size_opt_(GetMessageResultCount)WCHAR** GetMessageResult; // optional
} _GetMessageResponse;

typedef struct _HasErrors _HasErrors;

// typeDescription: n/a
typedef struct _HasErrorsResponse 
{
    BOOL HasErrorsResult;
} _HasErrorsResponse;

typedef struct _GetErrors _GetErrors;

// typeDescription: n/a
typedef struct _GetErrorsResponse 
{
    unsigned int GetErrorsResultCount;
    _Field_size_opt_(GetErrorsResultCount)WCHAR** GetErrorsResult; // optional
} _GetErrorsResponse;

typedef struct _HasWarnings _HasWarnings;

// typeDescription: n/a
typedef struct _HasWarningsResponse 
{
    BOOL HasWarningsResult;
} _HasWarningsResponse;

typedef struct _GetWarnings _GetWarnings;

// typeDescription: n/a
typedef struct _GetWarningsResponse 
{
    unsigned int GetWarningsResultCount;
    _Field_size_opt_(GetWarningsResultCount)WCHAR** GetWarningsResult; // optional
} _GetWarningsResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: GetNamesOfMethods ("http://tempuri.org/")
        // c type: _GetNamesOfMethods
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMethods
        WS_ELEMENT_DESCRIPTION GetNamesOfMethods;
        
        // xml element: GetNamesOfMethodsResponse ("http://tempuri.org/")
        // c type: _GetNamesOfMethodsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMethodsResponse
        WS_ELEMENT_DESCRIPTION GetNamesOfMethodsResponse;
        
        // xml element: GetNamesOfMethodsOfAssayType ("http://tempuri.org/")
        // c type: _GetNamesOfMethodsOfAssayType
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMethodsOfAssayType
        WS_ELEMENT_DESCRIPTION GetNamesOfMethodsOfAssayType;
        
        // xml element: GetNamesOfMethodsOfAssayTypeResponse ("http://tempuri.org/")
        // c type: _GetNamesOfMethodsOfAssayTypeResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMethodsOfAssayTypeResponse
        WS_ELEMENT_DESCRIPTION GetNamesOfMethodsOfAssayTypeResponse;
        
        // xml element: GetAssayTypesOfAllMethods ("http://tempuri.org/")
        // c type: _GetAssayTypesOfAllMethods
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypesOfAllMethods
        WS_ELEMENT_DESCRIPTION GetAssayTypesOfAllMethods;
        
        // xml element: GetAssayTypesOfAllMethodsResponse ("http://tempuri.org/")
        // c type: _GetAssayTypesOfAllMethodsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypesOfAllMethodsResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypesOfAllMethodsResponse;
        
        // xml element: GetNameOfCurrentMethod ("http://tempuri.org/")
        // c type: _GetNameOfCurrentMethod
        // elementDescription: tempuri_org_xsd.globalElements.GetNameOfCurrentMethod
        WS_ELEMENT_DESCRIPTION GetNameOfCurrentMethod;
        
        // xml element: GetNameOfCurrentMethodResponse ("http://tempuri.org/")
        // c type: _GetNameOfCurrentMethodResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNameOfCurrentMethodResponse
        WS_ELEMENT_DESCRIPTION GetNameOfCurrentMethodResponse;
        
        // xml element: GetAssayTypeOfCurrentMethod ("http://tempuri.org/")
        // c type: _GetAssayTypeOfCurrentMethod
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfCurrentMethod
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfCurrentMethod;
        
        // xml element: GetAssayTypeOfCurrentMethodResponse ("http://tempuri.org/")
        // c type: _GetAssayTypeOfCurrentMethodResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfCurrentMethodResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfCurrentMethodResponse;
        
        // xml element: GetAssayTypeOfMethod ("http://tempuri.org/")
        // c type: _GetAssayTypeOfMethod
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfMethod
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfMethod;
        
        // xml element: GetAssayTypeOfMethodResponse ("http://tempuri.org/")
        // c type: _GetAssayTypeOfMethodResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfMethodResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfMethodResponse;
        
        // xml element: GetNamesOfRunsets ("http://tempuri.org/")
        // c type: _GetNamesOfRunsets
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfRunsets
        WS_ELEMENT_DESCRIPTION GetNamesOfRunsets;
        
        // xml element: GetNamesOfRunsetsResponse ("http://tempuri.org/")
        // c type: _GetNamesOfRunsetsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfRunsetsResponse
        WS_ELEMENT_DESCRIPTION GetNamesOfRunsetsResponse;
        
        // xml element: GetNamesOfRunsetsOfAssayType ("http://tempuri.org/")
        // c type: _GetNamesOfRunsetsOfAssayType
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfRunsetsOfAssayType
        WS_ELEMENT_DESCRIPTION GetNamesOfRunsetsOfAssayType;
        
        // xml element: GetNamesOfRunsetsOfAssayTypeResponse ("http://tempuri.org/")
        // c type: _GetNamesOfRunsetsOfAssayTypeResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfRunsetsOfAssayTypeResponse
        WS_ELEMENT_DESCRIPTION GetNamesOfRunsetsOfAssayTypeResponse;
        
        // xml element: GetAssayTypesOfAllRunsets ("http://tempuri.org/")
        // c type: _GetAssayTypesOfAllRunsets
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypesOfAllRunsets
        WS_ELEMENT_DESCRIPTION GetAssayTypesOfAllRunsets;
        
        // xml element: GetAssayTypesOfAllRunsetsResponse ("http://tempuri.org/")
        // c type: _GetAssayTypesOfAllRunsetsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypesOfAllRunsetsResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypesOfAllRunsetsResponse;
        
        // xml element: GetNameOfCurrentRunset ("http://tempuri.org/")
        // c type: _GetNameOfCurrentRunset
        // elementDescription: tempuri_org_xsd.globalElements.GetNameOfCurrentRunset
        WS_ELEMENT_DESCRIPTION GetNameOfCurrentRunset;
        
        // xml element: GetNameOfCurrentRunsetResponse ("http://tempuri.org/")
        // c type: _GetNameOfCurrentRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNameOfCurrentRunsetResponse
        WS_ELEMENT_DESCRIPTION GetNameOfCurrentRunsetResponse;
        
        // xml element: GetAssayTypeOfCurrentRunset ("http://tempuri.org/")
        // c type: _GetAssayTypeOfCurrentRunset
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfCurrentRunset
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfCurrentRunset;
        
        // xml element: GetAssayTypeOfCurrentRunsetResponse ("http://tempuri.org/")
        // c type: _GetAssayTypeOfCurrentRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfCurrentRunsetResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfCurrentRunsetResponse;
        
        // xml element: GetAssayTypeOfRunset ("http://tempuri.org/")
        // c type: _GetAssayTypeOfRunset
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfRunset
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfRunset;
        
        // xml element: GetAssayTypeOfRunsetResponse ("http://tempuri.org/")
        // c type: _GetAssayTypeOfRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAssayTypeOfRunsetResponse
        WS_ELEMENT_DESCRIPTION GetAssayTypeOfRunsetResponse;
        
        // xml element: GetMethodNamesOfRunset ("http://tempuri.org/")
        // c type: _GetMethodNamesOfRunset
        // elementDescription: tempuri_org_xsd.globalElements.GetMethodNamesOfRunset
        WS_ELEMENT_DESCRIPTION GetMethodNamesOfRunset;
        
        // xml element: GetMethodNamesOfRunsetResponse ("http://tempuri.org/")
        // c type: _GetMethodNamesOfRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetMethodNamesOfRunsetResponse
        WS_ELEMENT_DESCRIPTION GetMethodNamesOfRunsetResponse;
        
        // xml element: SelectMethod ("http://tempuri.org/")
        // c type: _SelectMethod
        // elementDescription: tempuri_org_xsd.globalElements.SelectMethod
        WS_ELEMENT_DESCRIPTION SelectMethod;
        
        // xml element: SelectMethodResponse ("http://tempuri.org/")
        // c type: _SelectMethodResponse
        // elementDescription: tempuri_org_xsd.globalElements.SelectMethodResponse
        WS_ELEMENT_DESCRIPTION SelectMethodResponse;
        
        // xml element: SelectRunset ("http://tempuri.org/")
        // c type: _SelectRunset
        // elementDescription: tempuri_org_xsd.globalElements.SelectRunset
        WS_ELEMENT_DESCRIPTION SelectRunset;
        
        // xml element: SelectRunsetResponse ("http://tempuri.org/")
        // c type: _SelectRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.SelectRunsetResponse
        WS_ELEMENT_DESCRIPTION SelectRunsetResponse;
        
        // xml element: CreateRunset ("http://tempuri.org/")
        // c type: _CreateRunset
        // elementDescription: tempuri_org_xsd.globalElements.CreateRunset
        WS_ELEMENT_DESCRIPTION CreateRunset;
        
        // xml element: CreateRunsetResponse ("http://tempuri.org/")
        // c type: _CreateRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.CreateRunsetResponse
        WS_ELEMENT_DESCRIPTION CreateRunsetResponse;
        
        // xml element: SetSamplePlateId ("http://tempuri.org/")
        // c type: _SetSamplePlateId
        // elementDescription: tempuri_org_xsd.globalElements.SetSamplePlateId
        WS_ELEMENT_DESCRIPTION SetSamplePlateId;
        
        // xml element: SetSamplePlateIdResponse ("http://tempuri.org/")
        // c type: _SetSamplePlateIdResponse
        // elementDescription: tempuri_org_xsd.globalElements.SetSamplePlateIdResponse
        WS_ELEMENT_DESCRIPTION SetSamplePlateIdResponse;
        
        // xml element: GetSamplePlateId ("http://tempuri.org/")
        // c type: _GetSamplePlateId
        // elementDescription: tempuri_org_xsd.globalElements.GetSamplePlateId
        WS_ELEMENT_DESCRIPTION GetSamplePlateId;
        
        // xml element: GetSamplePlateIdResponse ("http://tempuri.org/")
        // c type: _GetSamplePlateIdResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetSamplePlateIdResponse
        WS_ELEMENT_DESCRIPTION GetSamplePlateIdResponse;
        
        // xml element: GetCurrentSamplePlateId ("http://tempuri.org/")
        // c type: _GetCurrentSamplePlateId
        // elementDescription: tempuri_org_xsd.globalElements.GetCurrentSamplePlateId
        WS_ELEMENT_DESCRIPTION GetCurrentSamplePlateId;
        
        // xml element: GetCurrentSamplePlateIdResponse ("http://tempuri.org/")
        // c type: _GetCurrentSamplePlateIdResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetCurrentSamplePlateIdResponse
        WS_ELEMENT_DESCRIPTION GetCurrentSamplePlateIdResponse;
        
        // xml element: MoveSamplePlateTrayOut ("http://tempuri.org/")
        // c type: _MoveSamplePlateTrayOut
        // elementDescription: tempuri_org_xsd.globalElements.MoveSamplePlateTrayOut
        WS_ELEMENT_DESCRIPTION MoveSamplePlateTrayOut;
        
        // xml element: MoveSamplePlateTrayOutResponse ("http://tempuri.org/")
        // c type: _MoveSamplePlateTrayOutResponse
        // elementDescription: tempuri_org_xsd.globalElements.MoveSamplePlateTrayOutResponse
        WS_ELEMENT_DESCRIPTION MoveSamplePlateTrayOutResponse;
        
        // xml element: MoveSamplePlateTrayIn ("http://tempuri.org/")
        // c type: _MoveSamplePlateTrayIn
        // elementDescription: tempuri_org_xsd.globalElements.MoveSamplePlateTrayIn
        WS_ELEMENT_DESCRIPTION MoveSamplePlateTrayIn;
        
        // xml element: MoveSamplePlateTrayInResponse ("http://tempuri.org/")
        // c type: _MoveSamplePlateTrayInResponse
        // elementDescription: tempuri_org_xsd.globalElements.MoveSamplePlateTrayInResponse
        WS_ELEMENT_DESCRIPTION MoveSamplePlateTrayInResponse;
        
        // xml element: StartSelectedRunset ("http://tempuri.org/")
        // c type: _StartSelectedRunset
        // elementDescription: tempuri_org_xsd.globalElements.StartSelectedRunset
        WS_ELEMENT_DESCRIPTION StartSelectedRunset;
        
        // xml element: StartSelectedRunsetResponse ("http://tempuri.org/")
        // c type: _StartSelectedRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.StartSelectedRunsetResponse
        WS_ELEMENT_DESCRIPTION StartSelectedRunsetResponse;
        
        // xml element: StartSelectedRunsetFrom ("http://tempuri.org/")
        // c type: _StartSelectedRunsetFrom
        // elementDescription: tempuri_org_xsd.globalElements.StartSelectedRunsetFrom
        WS_ELEMENT_DESCRIPTION StartSelectedRunsetFrom;
        
        // xml element: StartSelectedRunsetFromResponse ("http://tempuri.org/")
        // c type: _StartSelectedRunsetFromResponse
        // elementDescription: tempuri_org_xsd.globalElements.StartSelectedRunsetFromResponse
        WS_ELEMENT_DESCRIPTION StartSelectedRunsetFromResponse;
        
        // xml element: PauseRunsetAfter ("http://tempuri.org/")
        // c type: _PauseRunsetAfter
        // elementDescription: tempuri_org_xsd.globalElements.PauseRunsetAfter
        WS_ELEMENT_DESCRIPTION PauseRunsetAfter;
        
        // xml element: PauseRunsetAfterResponse ("http://tempuri.org/")
        // c type: _PauseRunsetAfterResponse
        // elementDescription: tempuri_org_xsd.globalElements.PauseRunsetAfterResponse
        WS_ELEMENT_DESCRIPTION PauseRunsetAfterResponse;
        
        // xml element: ResumeRunset ("http://tempuri.org/")
        // c type: _ResumeRunset
        // elementDescription: tempuri_org_xsd.globalElements.ResumeRunset
        WS_ELEMENT_DESCRIPTION ResumeRunset;
        
        // xml element: ResumeRunsetResponse ("http://tempuri.org/")
        // c type: _ResumeRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.ResumeRunsetResponse
        WS_ELEMENT_DESCRIPTION ResumeRunsetResponse;
        
        // xml element: ResetRunset ("http://tempuri.org/")
        // c type: _ResetRunset
        // elementDescription: tempuri_org_xsd.globalElements.ResetRunset
        WS_ELEMENT_DESCRIPTION ResetRunset;
        
        // xml element: ResetRunsetResponse ("http://tempuri.org/")
        // c type: _ResetRunsetResponse
        // elementDescription: tempuri_org_xsd.globalElements.ResetRunsetResponse
        WS_ELEMENT_DESCRIPTION ResetRunsetResponse;
        
        // xml element: AbortScript ("http://tempuri.org/")
        // c type: _AbortScript
        // elementDescription: tempuri_org_xsd.globalElements.AbortScript
        WS_ELEMENT_DESCRIPTION AbortScript;
        
        // xml element: AbortScriptResponse ("http://tempuri.org/")
        // c type: _AbortScriptResponse
        // elementDescription: tempuri_org_xsd.globalElements.AbortScriptResponse
        WS_ELEMENT_DESCRIPTION AbortScriptResponse;
        
        // xml element: LeaveStandby ("http://tempuri.org/")
        // c type: _LeaveStandby
        // elementDescription: tempuri_org_xsd.globalElements.LeaveStandby
        WS_ELEMENT_DESCRIPTION LeaveStandby;
        
        // xml element: LeaveStandbyResponse ("http://tempuri.org/")
        // c type: _LeaveStandbyResponse
        // elementDescription: tempuri_org_xsd.globalElements.LeaveStandbyResponse
        WS_ELEMENT_DESCRIPTION LeaveStandbyResponse;
        
        // xml element: SetStandbyAfterFinish ("http://tempuri.org/")
        // c type: _SetStandbyAfterFinish
        // elementDescription: tempuri_org_xsd.globalElements.SetStandbyAfterFinish
        WS_ELEMENT_DESCRIPTION SetStandbyAfterFinish;
        
        // xml element: SetStandbyAfterFinishResponse ("http://tempuri.org/")
        // c type: _SetStandbyAfterFinishResponse
        // elementDescription: tempuri_org_xsd.globalElements.SetStandbyAfterFinishResponse
        WS_ELEMENT_DESCRIPTION SetStandbyAfterFinishResponse;
        
        // xml element: GetStandbyAfterFinish ("http://tempuri.org/")
        // c type: _GetStandbyAfterFinish
        // elementDescription: tempuri_org_xsd.globalElements.GetStandbyAfterFinish
        WS_ELEMENT_DESCRIPTION GetStandbyAfterFinish;
        
        // xml element: GetStandbyAfterFinishResponse ("http://tempuri.org/")
        // c type: _GetStandbyAfterFinishResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetStandbyAfterFinishResponse
        WS_ELEMENT_DESCRIPTION GetStandbyAfterFinishResponse;
        
        // xml element: GetNamesOfMaintenanceProcedures ("http://tempuri.org/")
        // c type: _GetNamesOfMaintenanceProcedures
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMaintenanceProcedures
        WS_ELEMENT_DESCRIPTION GetNamesOfMaintenanceProcedures;
        
        // xml element: GetNamesOfMaintenanceProceduresResponse ("http://tempuri.org/")
        // c type: _GetNamesOfMaintenanceProceduresResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNamesOfMaintenanceProceduresResponse
        WS_ELEMENT_DESCRIPTION GetNamesOfMaintenanceProceduresResponse;
        
        // xml element: RunMaintenanceProcedure ("http://tempuri.org/")
        // c type: _RunMaintenanceProcedure
        // elementDescription: tempuri_org_xsd.globalElements.RunMaintenanceProcedure
        WS_ELEMENT_DESCRIPTION RunMaintenanceProcedure;
        
        // xml element: RunMaintenanceProcedureResponse ("http://tempuri.org/")
        // c type: _RunMaintenanceProcedureResponse
        // elementDescription: tempuri_org_xsd.globalElements.RunMaintenanceProcedureResponse
        WS_ELEMENT_DESCRIPTION RunMaintenanceProcedureResponse;
        
        // xml element: GetOperationMode ("http://tempuri.org/")
        // c type: _GetOperationMode
        // elementDescription: tempuri_org_xsd.globalElements.GetOperationMode
        WS_ELEMENT_DESCRIPTION GetOperationMode;
        
        // xml element: GetOperationModeResponse ("http://tempuri.org/")
        // c type: _GetOperationModeResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetOperationModeResponse
        WS_ELEMENT_DESCRIPTION GetOperationModeResponse;
        
        // xml element: IsChipDocked ("http://tempuri.org/")
        // c type: _IsChipDocked
        // elementDescription: tempuri_org_xsd.globalElements.IsChipDocked
        WS_ELEMENT_DESCRIPTION IsChipDocked;
        
        // xml element: IsChipDockedResponse ("http://tempuri.org/")
        // c type: _IsChipDockedResponse
        // elementDescription: tempuri_org_xsd.globalElements.IsChipDockedResponse
        WS_ELEMENT_DESCRIPTION IsChipDockedResponse;
        
        // xml element: IsSamplePlateTrayIn ("http://tempuri.org/")
        // c type: _IsSamplePlateTrayIn
        // elementDescription: tempuri_org_xsd.globalElements.IsSamplePlateTrayIn
        WS_ELEMENT_DESCRIPTION IsSamplePlateTrayIn;
        
        // xml element: IsSamplePlateTrayInResponse ("http://tempuri.org/")
        // c type: _IsSamplePlateTrayInResponse
        // elementDescription: tempuri_org_xsd.globalElements.IsSamplePlateTrayInResponse
        WS_ELEMENT_DESCRIPTION IsSamplePlateTrayInResponse;
        
        // xml element: HasMessage ("http://tempuri.org/")
        // c type: _HasMessage
        // elementDescription: tempuri_org_xsd.globalElements.HasMessage
        WS_ELEMENT_DESCRIPTION HasMessage;
        
        // xml element: HasMessageResponse ("http://tempuri.org/")
        // c type: _HasMessageResponse
        // elementDescription: tempuri_org_xsd.globalElements.HasMessageResponse
        WS_ELEMENT_DESCRIPTION HasMessageResponse;
        
        // xml element: GetMessage ("http://tempuri.org/")
        // c type: _GetMessage
        // elementDescription: tempuri_org_xsd.globalElements.GetMessage
        WS_ELEMENT_DESCRIPTION GetMessage;
        
        // xml element: GetMessageResponse ("http://tempuri.org/")
        // c type: _GetMessageResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetMessageResponse
        WS_ELEMENT_DESCRIPTION GetMessageResponse;
        
        // xml element: HasErrors ("http://tempuri.org/")
        // c type: _HasErrors
        // elementDescription: tempuri_org_xsd.globalElements.HasErrors
        WS_ELEMENT_DESCRIPTION HasErrors;
        
        // xml element: HasErrorsResponse ("http://tempuri.org/")
        // c type: _HasErrorsResponse
        // elementDescription: tempuri_org_xsd.globalElements.HasErrorsResponse
        WS_ELEMENT_DESCRIPTION HasErrorsResponse;
        
        // xml element: GetErrors ("http://tempuri.org/")
        // c type: _GetErrors
        // elementDescription: tempuri_org_xsd.globalElements.GetErrors
        WS_ELEMENT_DESCRIPTION GetErrors;
        
        // xml element: GetErrorsResponse ("http://tempuri.org/")
        // c type: _GetErrorsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetErrorsResponse
        WS_ELEMENT_DESCRIPTION GetErrorsResponse;
        
        // xml element: HasWarnings ("http://tempuri.org/")
        // c type: _HasWarnings
        // elementDescription: tempuri_org_xsd.globalElements.HasWarnings
        WS_ELEMENT_DESCRIPTION HasWarnings;
        
        // xml element: HasWarningsResponse ("http://tempuri.org/")
        // c type: _HasWarningsResponse
        // elementDescription: tempuri_org_xsd.globalElements.HasWarningsResponse
        WS_ELEMENT_DESCRIPTION HasWarningsResponse;
        
        // xml element: GetWarnings ("http://tempuri.org/")
        // c type: _GetWarnings
        // elementDescription: tempuri_org_xsd.globalElements.GetWarnings
        WS_ELEMENT_DESCRIPTION GetWarnings;
        
        // xml element: GetWarningsResponse ("http://tempuri.org/")
        // c type: _GetWarningsResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetWarningsResponse
        WS_ELEMENT_DESCRIPTION GetWarningsResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION GetNamesOfMethods;
        WS_STRUCT_DESCRIPTION GetNamesOfMethodsResponse;
        WS_STRUCT_DESCRIPTION GetNamesOfMethodsOfAssayType;
        WS_STRUCT_DESCRIPTION GetNamesOfMethodsOfAssayTypeResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypesOfAllMethods;
        WS_STRUCT_DESCRIPTION GetAssayTypesOfAllMethodsResponse;
        WS_STRUCT_DESCRIPTION GetNameOfCurrentMethod;
        WS_STRUCT_DESCRIPTION GetNameOfCurrentMethodResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfCurrentMethod;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfCurrentMethodResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfMethod;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfMethodResponse;
        WS_STRUCT_DESCRIPTION GetNamesOfRunsets;
        WS_STRUCT_DESCRIPTION GetNamesOfRunsetsResponse;
        WS_STRUCT_DESCRIPTION GetNamesOfRunsetsOfAssayType;
        WS_STRUCT_DESCRIPTION GetNamesOfRunsetsOfAssayTypeResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypesOfAllRunsets;
        WS_STRUCT_DESCRIPTION GetAssayTypesOfAllRunsetsResponse;
        WS_STRUCT_DESCRIPTION GetNameOfCurrentRunset;
        WS_STRUCT_DESCRIPTION GetNameOfCurrentRunsetResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfCurrentRunset;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfCurrentRunsetResponse;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfRunset;
        WS_STRUCT_DESCRIPTION GetAssayTypeOfRunsetResponse;
        WS_STRUCT_DESCRIPTION GetMethodNamesOfRunset;
        WS_STRUCT_DESCRIPTION GetMethodNamesOfRunsetResponse;
        WS_STRUCT_DESCRIPTION SelectMethod;
        WS_STRUCT_DESCRIPTION SelectMethodResponse;
        WS_STRUCT_DESCRIPTION SelectRunset;
        WS_STRUCT_DESCRIPTION SelectRunsetResponse;
        WS_STRUCT_DESCRIPTION CreateRunset;
        WS_STRUCT_DESCRIPTION CreateRunsetResponse;
        WS_STRUCT_DESCRIPTION SetSamplePlateId;
        WS_STRUCT_DESCRIPTION SetSamplePlateIdResponse;
        WS_STRUCT_DESCRIPTION GetSamplePlateId;
        WS_STRUCT_DESCRIPTION GetSamplePlateIdResponse;
        WS_STRUCT_DESCRIPTION GetCurrentSamplePlateId;
        WS_STRUCT_DESCRIPTION GetCurrentSamplePlateIdResponse;
        WS_STRUCT_DESCRIPTION MoveSamplePlateTrayOut;
        WS_STRUCT_DESCRIPTION MoveSamplePlateTrayOutResponse;
        WS_STRUCT_DESCRIPTION MoveSamplePlateTrayIn;
        WS_STRUCT_DESCRIPTION MoveSamplePlateTrayInResponse;
        WS_STRUCT_DESCRIPTION StartSelectedRunset;
        WS_STRUCT_DESCRIPTION StartSelectedRunsetResponse;
        WS_STRUCT_DESCRIPTION StartSelectedRunsetFrom;
        WS_STRUCT_DESCRIPTION StartSelectedRunsetFromResponse;
        WS_STRUCT_DESCRIPTION PauseRunsetAfter;
        WS_STRUCT_DESCRIPTION PauseRunsetAfterResponse;
        WS_STRUCT_DESCRIPTION ResumeRunset;
        WS_STRUCT_DESCRIPTION ResumeRunsetResponse;
        WS_STRUCT_DESCRIPTION ResetRunset;
        WS_STRUCT_DESCRIPTION ResetRunsetResponse;
        WS_STRUCT_DESCRIPTION AbortScript;
        WS_STRUCT_DESCRIPTION AbortScriptResponse;
        WS_STRUCT_DESCRIPTION LeaveStandby;
        WS_STRUCT_DESCRIPTION LeaveStandbyResponse;
        WS_STRUCT_DESCRIPTION SetStandbyAfterFinish;
        WS_STRUCT_DESCRIPTION SetStandbyAfterFinishResponse;
        WS_STRUCT_DESCRIPTION GetStandbyAfterFinish;
        WS_STRUCT_DESCRIPTION GetStandbyAfterFinishResponse;
        WS_STRUCT_DESCRIPTION GetNamesOfMaintenanceProcedures;
        WS_STRUCT_DESCRIPTION GetNamesOfMaintenanceProceduresResponse;
        WS_STRUCT_DESCRIPTION RunMaintenanceProcedure;
        WS_STRUCT_DESCRIPTION RunMaintenanceProcedureResponse;
        WS_STRUCT_DESCRIPTION GetOperationMode;
        WS_STRUCT_DESCRIPTION GetOperationModeResponse;
        WS_STRUCT_DESCRIPTION IsChipDocked;
        WS_STRUCT_DESCRIPTION IsChipDockedResponse;
        WS_STRUCT_DESCRIPTION IsSamplePlateTrayIn;
        WS_STRUCT_DESCRIPTION IsSamplePlateTrayInResponse;
        WS_STRUCT_DESCRIPTION HasMessage;
        WS_STRUCT_DESCRIPTION HasMessageResponse;
        WS_STRUCT_DESCRIPTION GetMessage;
        WS_STRUCT_DESCRIPTION GetMessageResponse;
        WS_STRUCT_DESCRIPTION HasErrors;
        WS_STRUCT_DESCRIPTION HasErrorsResponse;
        WS_STRUCT_DESCRIPTION GetErrors;
        WS_STRUCT_DESCRIPTION GetErrorsResponse;
        WS_STRUCT_DESCRIPTION HasWarnings;
        WS_STRUCT_DESCRIPTION HasWarningsResponse;
        WS_STRUCT_DESCRIPTION GetWarnings;
        WS_STRUCT_DESCRIPTION GetWarningsResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

